server:
  port: 8081 # Auth Service runs on 8081

spring:
  application:
    name: auth-service
  datasource:
    # Note: Connecting to auth_db specifically
    url: jdbc:postgresql://localhost:5432/auth_db
    username: admin
    password: password
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate # Production standard: Flyway handles schema, Hibernate validates it
    properties:
      hibernate:
        format_sql: true
  flyway:
    enabled: true
    baseline-on-migrate: true